We assume that there is a catalog item created with arb settings
		trialOccurrences = 1
		totalOccurrences = 12
		interval_length = 1
		trialAmount = 10

	Step 1. Register as a new user it will login the new user if registration  is successfull
			register url: /users/users/register
			login url: /users/users/login

			note: in the process of register if we enable the __APP_REGISTRATION_EMAIL_VERIFICATION for mail verification there is a issue with SwiftMailer

Fatal error: Uncaught exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [] does not comply with RFC 2822, 3.6.2.' in /var/www/dev/vendors/swift_mailer/classes/Swift/Mime/Headers/MailboxHeader.php:309 Stack trace: #0 /var/www/dev/vendors/swift_mailer/classes/Swift/Mime/Headers/MailboxHeader.php(239): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('') #1 /var/www/dev/vendors/swift_mailer/classes/Swift/Mime/Headers/MailboxHeader.php(97): 		Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array) #2 /var/www/dev/vendors/swift_mailer/classes/Swift/Mime/Headers/MailboxHeader.php(61): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array) #3 /var/www/dev/vendors/swift_mailer/classes/Swift/Mime/SimpleMimeEntity.php(571): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array) #4 /var/www/dev/vendors/swift_mailer/classes/Swift/Mime/SimpleMessage.php(199): Swift_Mime_SimpleMimeEntity->_setHeaderFieldModel('From', Array) #5 /var/www/dev/app/controllers/components/swift_mailer.php(331): Swi in /var/www/dev/vendors/swift_mailer/classes/Swift/Mime/Headers/MailboxHeader.php on line 309

			Members plugin is called which checks that the login user is a paid member or free member
			based on the role settings in .ini file.
			 __USERS_PAID_EXPIRED_ROLE = users // normal non paid
			 __USERS_PAID_ROLE = administrators // paid.

	Step 2. After checking user role if its a paid member
		then it takes the user to  __USERS_PAID_ROLE_REDIRECT else if user is a free member then it will take user to catalog item page where the membership plans are showed. Catalog item id comes from settings.

	Step 3. Select Plan from CatalogItems and addToCart
			And Then checkout

	Step 4. Fill Required information for checkout
			There if arb_settings given for selected Catalog Item. Then it create this payment arb payment info :
						Payment Mode -> Paypal
						CC Num -> 4163798209619463
						CC Exp -> 05/2016

						Payment Mode -> Authorize
						CC Num -> 4111111111111111
						CC Exp -> 05/2016

			And after giving info click Checkout if transaction is successfull it will take you to
					__ORDERS_CHECKOUT_REDIRECT in which the settings are defined to redirect the page

				eg url: http://leasesimple.localhost/members/members/set_paid_user_role

	Step 5. After verify payment it will change user role to __USERS_PAID_ROLE  settings and redirect to  __USERS_PAID_ROLE_REDIRECT

	url's list :

	http://leasesimple.localhost/users/users/register
	http://leasesimple.localhost/users/users/login
	http://leasesimple.localhost/catalogs/catalog_items/view/46
	http://leasesimple.localhost/orders/order_transactions/checkout
	http://leasesimple.localhost/members/members/set_paid_user_role
	http://leasesimple.localhost/members/members/is_member